### ISSUE TITLE
Crash on released apk

### ISSUE THREAD

**Issue by Goooler** [Goooler/DemoApp#8]
```log
2022-01-25 00:14:25.637 8875-8875/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.goooler.demoapp, PID: 8875
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.goooler.demoapp/io.goooler.demoapp.main.ui.MainActivity}: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3786)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8030)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
        at x4.c.a(SourceFile:1)
        at r4.a.onCreate(SourceFile:2)
        at io.goooler.demoapp.main.ui.MainActivity.onCreate(SourceFile:1)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3595)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3786) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:8030) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) 
```

`MainActivity` extends `BaseBindingActivity` with generic argument `MainActivityBinding`:

https://github.com/Goooler/DemoApp/blob/cc12a2f8afee4ddcb601dc46b64815c3a0d22af1/main/src/main/kotlin/io/goooler/demoapp/main/ui/MainActivity.kt#L18-L21

`binding` instantiated by `inflateBinding` extension in `BaseBindingActivity`:
https://github.com/Goooler/DemoApp/blob/cc12a2f8afee4ddcb601dc46b64815c3a0d22af1/common/src/main/kotlin/io/goooler/demoapp/common/base/binding/BaseBindingActivity.kt#L8-L19

`inflateBinding` generate binding by reflection:
https://github.com/Goooler/DemoApp/blob/cc12a2f8afee4ddcb601dc46b64815c3a0d22af1/common/src/main/kotlin/io/goooler/demoapp/common/util/CommonExtensions.kt#L297-L303

**Comment by Goooler** [comment]
Since 856d4c30a86fc49c0bd836b23867b011d1ee9c6b.

**Comment by Goooler** [comment]
Caused by updating `AGP 7.0.0-beta01` with `android.enableR8.fullMode=true` enabled.
If I disable `android.enableR8.fullMode=true`, no crash happend.

**Comment by Goooler** [comment]
Have not been fixed in AGP `7.0.4` or `7.1.0-rc01` or `AGP 7.2.0-alpha07`.

**Comment by Goooler** [comment]
https://github.com/Goooler/DemoApp/blob/cc12a2f8afee4ddcb601dc46b64815c3a0d22af1/common/src/main/kotlin/io/goooler/demoapp/common/base/binding/BaseBindingActivity.kt#L8-L19

**Comment by Goooler** [comment]
Decompile `MainActivity` with `android.enableR8.fullMode=true` enabled:
```java
@Route(path = "/main/")
public final class MainActivity extends a {
  ...
}
```

Decompile `MainActivity` with `android.enableR8.fullMode=true` disabled:
```java
@Route(path = "/main/")
public final class MainActivity extends a<MainActivityBinding> {
  ...
}
```

So r8 fullMode erase the generic type on `MainActivity`'s super class, make `javaClass.genericSuperclass as ParameterizedType` throw `ClassCastException`, seems this behavior starts from AGP 7.0.0-beta01 and I already add `-keepattributes Signature` rule in proguard files.

**Comment by Goooler** [comment]
Here is the `MainActivity` decompiled from dex:
```java
public final class MainActivity extends a {
  ...
}
```
No generic type on `a` class.

**Comment by Goooler** [comment]
Still showing after AGP 7.1, to solve this problem absolutely, should wait Hilt to release a new version that supports new R8 rules.

**Comment by Goooler** [comment]
After #13 & #31, solved.
